package dev.gltfexport.export;

import java.lang.reflect.Field;
import java.lang.reflect.Method;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Optional;
import java.util.Set;

import com.mojang.blaze3d.vertex.PoseStack;
import com.mojang.blaze3d.vertex.VertexConsumer;
import dev.gltfexport.GltfExportClient;
import dev.gltfexport.export.SceneData.Joint;
import dev.gltfexport.export.SceneData.MaterialKey;
import dev.gltfexport.export.SceneData.Rig;
import dev.gltfexport.util.Refl;
import net.minecraft.client.model.geom.ModelPart;
import net.minecraft.client.renderer.texture.TextureAtlasSprite;
import org.joml.Matrix4f;
import org.joml.Vector3f;

/**
 * Converts a posed {@link ModelPart} tree into a skeleton (one bone per part, named after the part) plus geometry
 * rigidly skinned to those bones. Cubes are generated by vanilla's own {@code Cube#compile}, so UVs, mirroring and
 * hidden faces match the game exactly.
 */
public final class ModelRigger {
	private static final PoseStack.Pose IDENTITY = new PoseStack().last();
	private static Method cubeCompile;
	private static boolean warned;

	private final CaptureConsumer capture = new CaptureConsumer();
	private int tint = 0xFFFFFF;

	/**
	 * @param root      the part to start from (a model's root or a single submitted part)
	 * @param rootName  bone name for the root
	 * @param basePose  transform from the root's parent space to export space
	 * @param material  material for all faces
	 * @param sprite    if the model was submitted with an atlas sprite, its UVs are already sprite-relative
	 */
	public Rig rig(ModelPart root, String rigName, String rootName, Matrix4f basePose, MaterialKey material,
				   TextureAtlasSprite sprite, int tint) {
		this.tint = tint;
		Rig rig = new Rig(rigName);
		PoseStack ps = new PoseStack();
		ps.last().pose().set(basePose);
		walk(root, rootName, -1, ps, rig, material, new HashSet<>());
		return rig;
	}

	private void walk(ModelPart part, String name, int parent, PoseStack ps, Rig rig, MaterialKey material, Set<String> names) {
		if (!Refl.getBoolean(part, "visible", true)) return;
		ps.pushPose();
		part.translateAndRotate(ps);
		Matrix4f global = new Matrix4f(ps.last().pose());
		if (Math.abs(global.determinant()) < 1e-12f) {
			// scaled to zero: invisible, and non-invertible (cannot be a bone)
			ps.popPose();
			return;
		}

		String unique = name;
		for (int i = 2; !names.add(unique); i++) unique = name + "_" + i;
		int jointIndex = rig.joints.size();
		rig.joints.add(new Joint(unique, parent, global));

		if (!Refl.getBoolean(part, "skipDraw", false)) {
			for (Object cube : cubes(part)) {
				capture.clear();
				if (!compile(cube, capture)) continue;
				emit(global, rig, material, jointIndex);
			}
		}

		for (Map.Entry<String, ModelPart> child : children(part).entrySet()) {
			walk(child.getValue(), child.getKey(), jointIndex, ps, rig, material, names);
		}
		ps.popPose();
	}

	private void emit(Matrix4f global, Rig rig, MaterialKey material, int jointIndex) {
		SceneData.Prim prim = rig.prim(material);
		float[] p = new float[12];
		float[] t = new float[8];
		Vector3f v = new Vector3f();
		for (int q = 0; q < capture.quadCount(); q++) {
			for (int i = 0; i < 4; i++) {
				int vi = q * 4 + i;
				global.transformPosition(v.set(capture.x(vi), capture.y(vi), capture.z(vi)));
				p[i * 3] = v.x;
				p[i * 3 + 1] = v.y;
				p[i * 3 + 2] = v.z;
				t[i * 2] = capture.u(vi);
				t[i * 2 + 1] = capture.v(vi);
			}
			prim.addQuad(p, t, jointIndex, tint);
		}
	}

	@SuppressWarnings("unchecked")
	private static List<Object> cubes(ModelPart part) {
		Optional<Field> f = Refl.fieldNamedOrTyped(ModelPart.class, "cubes", List.class);
		if (f.isEmpty()) return List.of();
		try {
			Object v = f.get().get(part);
			return v instanceof List<?> l ? (List<Object>) l : List.of();
		} catch (ReflectiveOperationException e) {
			return List.of();
		}
	}

	@SuppressWarnings("unchecked")
	private static Map<String, ModelPart> children(ModelPart part) {
		Optional<Field> f = Refl.fieldNamedOrTyped(ModelPart.class, "children", Map.class);
		if (f.isEmpty()) return Map.of();
		try {
			Object v = f.get().get(part);
			return v instanceof Map<?, ?> m ? (Map<String, ModelPart>) m : Map.of();
		} catch (ReflectiveOperationException e) {
			return Map.of();
		}
	}

	private static boolean compile(Object cube, VertexConsumer out) {
		try {
			if (cubeCompile == null || !cubeCompile.getDeclaringClass().isInstance(cube)) {
				cubeCompile = Refl.findMethod(cube.getClass(), m -> m.getName().equals("compile")
						&& m.getParameterCount() >= 2
						&& m.getParameterTypes()[0] == PoseStack.Pose.class
						&& VertexConsumer.class.isAssignableFrom(m.getParameterTypes()[1]));
			}
			if (cubeCompile == null) {
				warnOnce("ModelPart.Cube#compile not found; entity geometry cannot be exported");
				return false;
			}
			Class<?>[] types = cubeCompile.getParameterTypes();
			Object[] args = new Object[types.length];
			args[0] = IDENTITY;
			args[1] = out;
			int ints = 0;
			for (int i = 2; i < types.length; i++) {
				if (types[i] == int.class) {
					// light, overlay, colour (white)
					args[i] = ints++ < 2 ? 0 : -1;
				} else {
					args[i] = Refl.defaultValue(types[i]);
				}
			}
			cubeCompile.invoke(cube, args);
			return true;
		} catch (ReflectiveOperationException | RuntimeException e) {
			warnOnce("Failed to compile model cube: " + e);
			return false;
		}
	}

	private static void warnOnce(String msg) {
		if (!warned) {
			warned = true;
			GltfExportClient.LOGGER.warn(msg);
		}
	}
}
